### ISSUE TITLE
Clear up documentation on loading LSCOLORS env var

### ISSUE THREAD

**Issue by cowang4** [sharkdp/lscolors#17]
Hello,

I think that the example in the README should show more clearly that the LSCOLORS env var should be loaded only once at the beginning of the program for performance.

Simply writing a comment saying that should suffice. Or, consider updating the example to pass that in as a reference to some coloring function, or declare it statically with lazy_static.

Thanks for the great crate!

**Comment by sharkdp** [comment]
Thank you for the feedback.

I think that's actually made reasonably clear by the API documentation, but feel free to suggest changes.
