### ISSUE TITLE
ls has default styles

### ISSUE THREAD

**Issue by tavianator** [sharkdp/lscolors#19]
If you do

    $ LS_COLORS="" ls --color

you'll still get colored output, because GNU ls has a set of default styles.  You can find them listed in `man dir_colors` (ls uses the following defaults: ...).  Or [here](https://github.com/coreutils/coreutils/blob/master/src/ls.c#L608).

Setting one thing in `LS_COLORS` doesn't override the rest of the defaults, so you can do something like

    $ LS_COLORS="ex=01:" ls --color

and only executables will change color, while directories etc. will stay like the defaults.

**Comment by sharkdp** [comment]
Thank you for reporting this. This should be supported.
