### ISSUE TITLE
Add support for all possible ANSI styles?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/lscolors#2]
In addition to bold, underline and italic, there are also:

* faint
* slow blink
* rapid blink
* dimmed
* hidden
* ...

see: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters

**Comment by tavianator** [comment]
Is it necessary to actually parse all of these?  Why not just pass whatever's in `LS_COLORS` through verbatim?

**Comment by sharkdp** [comment]
My idea was that this would result in a more robust handling of faulty `LS_COLORS` sequences. Also, it allows users of the library to do much more with the parsed styles:

- modify the style (e.g.: colorize according to LS_COLORS, but ignore bold/italic)
- Fall back from 24bit to 8bit sequences
- render the style in a different way (e.g. output HTML)
