### ISSUE TITLE
Release v0.5.0 is missing the non-musl .deb package 

### ISSUE THREAD

**Issue by nifr** [sharkdp/lscolors#20]
Hey David / @sharkdp,
first of all I'd like to thank you a thousand times for all these awesome rust cli applications/libraries you've released! :+1: :+1: :+1: 
Each of them is great, absolutely on-point and you have single-handedly greatly improved my terminal environment with every single one them. 

I'm using an `ansible` playbook to install all of them (`fd`, `hexyl`, ...) on basically any Debian based system I work with. I can share the playbook/roles in case you're interested.

I have included a variable that determines wether to use the `*-musl-*` variants if available (defaults to true) so I didn't recognize that my playbook was broken for the non-musl installation of the current release of `lscolors` until I updated my build system today.

Could you add the missing `.deb` to the release please? That'd be really cool and greatly appreciated.

Thanks in advance and again: kudos for all the great stuff you're sharing! :smile:

**Comment by sharkdp** [comment]
> Hey David / @sharkdp,
> first of all I'd like to thank you a thousand times for all these awesome rust cli applications/libraries you've released! +1 +1 +1
> Each of them is great, absolutely on-point and you have single-handedly greatly improved my terminal environment with every single one them.

Thank you very much for the kind words!! I'm always glad to hear feedback like this. Keeps me motivated :blush: 

> Could you add the missing `.deb` to the release please? That'd be really cool and greatly appreciated.

I re-ran the Job on Travis again, and now the file is correctly deployed. Not sure what happened there.
