### ISSUE TITLE
[feature request] API to style file paths that don't exist on disk

### ISSUE THREAD

**Issue by aswild** [sharkdp/lscolors#31]
### Use case

I have an arbitrary `&Path` that represents a normal file name, but it was programmatically generated and does not correspond to a file on disk (e.g. when inspecting a tarball), and I want a way to get the appropriate `Style` for it based on the file extension.

None of the existing APIs can do this:
* `style_for_path` calls `std::fs::symlink_metadata`, which fails if the path does not exist in the filesystem
* `style_for_path_with_metadata` could work, except that it's impossible to manually construct a `std::fs::Metadata` object
* `style_for_indicator` doesn't use the suffix_mapping table so I miss out on coloring files based on extension

### Proposed API

```rust
impl LsColors {
    pub fn style_for_regular_file<P: AsRef<Path>>(&self, path: P) -> Option<&Style>;
}
```

The result would be the same as `style_for_path_with_metadata` when that `Metadata` refers to a regular file.

### Implementation

I'm planning on forking and writing my own implementation of this anyway, and I'm happy to send a PR incorporating whatever feedback you may have.

**Comment by aswild** [comment]
After looking at the code more, I realized that my proposed `style_for_regular_file` is just exactly `style_for_path_with_metadata` when the `metadata` argument is `None`. I totally glossed over the fact that it takes an `Option`, I guess this is what I get for coding at 1am ;)

**Comment by sharkdp** [comment]
Glad it worked out. By the way, I'm always curious about possible use cases for `lscolors`, so I'd be glad to hear about new projects using `lscolors`.

**Comment by aswild** [comment]
I'm working on a Rust rewrite of a tool I call `pine`, which produces a colored file/directory hierarchy output like `tree(1)`, but instead of just reading from the filesystem it can read archives like tarballs or zip files, or get lists of files that belong to distro packages.  Basically an lscolors'd tree output of `bsdtar -tf ...` or `pacman -Ql ...`. It'll be public on github eventually when I get the core features working well enough.

My original python version has some dependency issues that don't let me use it outside of Arch systems, and the Rust port is turning into a good lesson on how to do nontrivial FFI into `libarchive`

**Comment by sharkdp** [comment]
Sounds great! I'd be very interested to see it when it goes public.

**Comment by aswild** [comment]
> Sounds great! I'd be very interested to see it when it goes public.

Here it is: https://github.com/aswild/pine. I got the minimum viable core features implemented, but it's still pretty barebones.

**Comment by sharkdp** [comment]
Nice - Congratulations!
