### ISSUE TITLE
Feature request: Always add ANSI coloring sequence,

### ISSUE THREAD

**Issue by nkh** [sharkdp/lscolors#32]
Hi, would it be possible to always have an ANSI coloring sequence even for files that are colored "no color", this makes it easier to use lscolors without having to parse it's output to see if the the sequences are there or  not.

some background, I am implementing my own version of fff, because I can, and I use lscolors in it (I asked you to make it an application, would be strange ot not use it), I need to take  substring from the colored file name and not having to deal with files that have the ansi sequences and those that are not simplify the logic 

FYI: https://gist.github.com/nkh/6144e0dfcaf5848c43fa962ad47be865

**Comment by sharkdp** [comment]
please see my comment in #33
