### ISSUE TITLE
Release a new version for the support of crossterm

### ISSUE THREAD

**Issue by zwpaper** [sharkdp/lscolors#34]
Lscolors have added the crossterm feature support in master for nearly a year, but not yet release a version, I am looking forward to using this feature in https://github.com/Peltoche/lsd/pull/452, could the maintainer release a newer version please, so that we don't have to implement it ourselves or use the master branch.

**Comment by sharkdp** [comment]
I released a new version: https://github.com/sharkdp/lscolors/releases/tag/v0.8.0
