### ISSUE TITLE
Support for bright/light colors

### ISSUE THREAD

**Issue by meain** [sharkdp/lscolors#39]
![Screenshot from 2022-01-17 10-03-48](https://user-images.githubusercontent.com/14259816/149708654-128ccb9c-1dd0-46e1-8796-d58db22113c9.png)

`lscolors` does not seem to parse 90-97 colors properly.

**Comment by sharkdp** [comment]
Thank you very much for your request. We should add support for this. I would hope that it's a straightforward change.
