### ISSUE TITLE
lscolors binary: accept paths as arguments (instead of STDIN)

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/lscolors#4]

**Comment by sharkdp** [comment]
@nkh This is now implemented and released in [v0.3.0](https://github.com/sharkdp/lscolors/releases/tag/v0.3.0). Would be great to get your feedback.

**Comment by nkh** [comment]
where is it documented?

**Comment by sharkdp** [comment]
It's not documented anywhere.
