### ISSUE TITLE
support crossterm 0.24 with it's new underline styles

### ISSUE THREAD

**Issue by fdncred** [sharkdp/lscolors#49]
It would be great to bump crossterm to 0.24 and build in support for their new underline styles. We use `lscolors` in [nushell ](https://github.com/nushell/nushell) and love it. Thanks for such a cool crate!

**Comment by sharkdp** [comment]
Thank you for the feedback!

**Comment by sharkdp** [comment]
Released as [v0.11.0](https://github.com/sharkdp/lscolors/releases/tag/v0.11.0)
