### ISSUE TITLE
Add color codes to parts that are not colored to simplify parsing

### ISSUE THREAD

**Issue by nkh** [sharkdp/lscolors#79]
use case:

 "path/path/colored_file" will have color codes for all parts
 
 "path/path/not_colored_file" will not have color codes for the not_colored_file which makes parsing the output more complicated than necessary

**Comment by tavianator** [comment]
The `LS_COLORS` key `no` sets the color of normal files, so if you set it to something, `not_colored_file` will also be colored.

Are you parsing the output of the `lscolors` binary?  It's probably better to use the library crate itself.

**Comment by nkh** [comment]
@tavianator I'll try setting "no"

I'm using the binary from a bash script.

**Comment by nkh** [comment]
@tavianator it sems that neither NORMAL nor FILE are handled

Here's an example where I changed both:

![screenshot_2023-12-15_21-15-52](https://github.com/sharkdp/lscolors/assets/45409/1b359c38-9864-4e1d-ac23-196311ac3c66)

ls will show a file not matching a pattern in the right color but lscolors doesn't seem to. In the example below *INSTALL* is colored but *file* isn't.

![screenshot_2023-12-15_21-16-42](https://github.com/sharkdp/lscolors/assets/45409/c602317f-c46b-4f71-80db-13c71d68cb2b)

**Comment by tavianator** [comment]
Right, I mixed up `no` (normal, non-file text) and `fi` (regular files).  But `fi` seems to work for me:

![Screenshot_20231215_153327](https://github.com/sharkdp/lscolors/assets/1692591/66113ec5-3ec8-4b4e-ba1e-2384fef04f10)

Can you paste your whole `LS_COLORS` variable?

**Comment by nkh** [comment]
@tavianator an update to a newer version fixed it. 

Note that **fi** needs to be set to *40* for lscolors to output color codes, setting it to *0* doesn't output color code 0.

**Comment by tavianator** [comment]
Right, 0 is treated basically the same as unset for most things
